### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by Bryntet** [cclark20/disc-golf-data#1]
Hello there! I work for a small media production company that has been dabbling in streaming disc-golf.

We're wondering what kind of license applies to the code in your repo, because then we don't have to work out how to scrape data from udisc ourselves haha 😅

Hope you're having a lovely day

//Edvin

**Comment by cclark20** [comment]
Hi! Thanks for your interest in the code and for reaching out. This project was just for fun, so I'm totally fine with you using it for your needs. Feel free to reach out if you have any questions or need any assistance with anything.
